###
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
    "email": "brauliochavez2509@gmail.com",
    "password": "123456",
    "name": "braulio",
    "lastname": "chavez"
}

###
POST http://localhost:8000/api/v1/auth/verify-acc?token=2cf64538bcf011dbc0cc44b4f190462abbc0413f343365780ca3e592e76cdffa


###
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
    "email": "brauliochaveza@gmail.com",
    "password": "123456"
}

###
POST http://localhost:8000/api/v1/auth/recover-password
Content-Type: application/json

{
    "email": "brauliochaveza@gmail.com"
}

###
POST http://localhost:8000/api/v1/auth/reset-password?token=f78c4a488bb4f8e9728e0fc71a14d7b7bc23677bed7cc84b898e74a27e7e2051
Content-Type: application/json

{
    "password": "123456"
}

### ---------------------------------REPORTS ---------------------------------
POST http://localhost:8000/api/v1/reports
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVhZDY3NTRmLWYzZDktNGUwMy04ZDQ1LWY4NzdhMjUzOTcxYyIsInJvbGUiOiJVU0VSIiwiY2FuUmVwb3J0Ijp0cnVlLCJpYXQiOjE3NzY4MDE1ODEsImV4cCI6MTc3Njg4Nzk4MX0.RPvQS0_CzT2BAIeXgSkYnn2Qgv2HbpMC3zW8twPGEvM

{
    "title": "Reporte de problemas de basura",
    "description": "Reporte detallado de problemas visualizados en la zona.",
    "category": "OTHER",
    "latitude": 19.2797,
    "longitude": -99.0054
}

###
GET http://localhost:8000/api/v1/reports
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVhZDY3NTRmLWYzZDktNGUwMy04ZDQ1LWY4NzdhMjUzOTcxYyIsInJvbGUiOiJVU0VSIiwiY2FuUmVwb3J0Ijp0cnVlLCJpYXQiOjE3NzY4MDE1ODEsImV4cCI6MTc3Njg4Nzk4MX0.RPvQS0_CzT2BAIeXgSkYnn2Qgv2HbpMC3zW8twPGEvM

###
GET http://localhost:8000/api/v1/reports?status=PENDING
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVhZDY3NTRmLWYzZDktNGUwMy04ZDQ1LWY4NzdhMjUzOTcxYyIsInJvbGUiOiJVU0VSIiwiY2FuUmVwb3J0Ijp0cnVlLCJpYXQiOjE3NzY2MTUxOTMsImV4cCI6MTc3NjcwMTU5M30.zAGuBizjAfs4YLEi0GAQi2Y2ynPBy2itI0IG67heZfI

###
GET http://localhost:8000/api/v1/reports/b5221ffc-51b0-48f1-821a-423a3c362f3e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVhZDY3NTRmLWYzZDktNGUwMy04ZDQ1LWY4NzdhMjUzOTcxYyIsInJvbGUiOiJVU0VSIiwiY2FuUmVwb3J0Ijp0cnVlLCJpYXQiOjE3NzY4MDE1ODEsImV4cCI6MTc3Njg4Nzk4MX0.RPvQS0_CzT2BAIeXgSkYnn2Qgv2HbpMC3zW8twPGEvM

###
PATCH http://localhost:8000/api/v1/reports/b5221ffc-51b0-48f1-821a-423a3c362f3e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVhZDY3NTRmLWYzZDktNGUwMy04ZDQ1LWY4NzdhMjUzOTcxYyIsInJvbGUiOiJVU0VSIiwiY2FuUmVwb3J0Ijp0cnVlLCJpYXQiOjE3NzY4MDE1ODEsImV4cCI6MTc3Njg4Nzk4MX0.RPvQS0_CzT2BAIeXgSkYnn2Qgv2HbpMC3zW8twPGEvM

{
    "title": "Reporte actualizado de problemas de basura",
    "description": "Descripción actualizada del reporte detallado de problemas visualizados en la zona.",
    "latitude": 19.4327,
    "longitude": -99.1333
}

###
PATCH http://localhost:8000/api/v1/reports/b5221ffc-51b0-48f1-821a-423a3c362f3e/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVhZDY3NTRmLWYzZDktNGUwMy04ZDQ1LWY4NzdhMjUzOTcxYyIsInJvbGUiOiJVU0VSIiwiY2FuUmVwb3J0Ijp0cnVlLCJpYXQiOjE3NzY4MDE1ODEsImV4cCI6MTc3Njg4Nzk4MX0.RPvQS0_CzT2BAIeXgSkYnn2Qgv2HbpMC3zW8twPGEvM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

###
PATCH  http://localhost:8000/api/v1/reports/92dda4e6-4cef-425c-a3d4-4c26f829cea6/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVhZDY3NTRmLWYzZDktNGUwMy04ZDQ1LWY4NzdhMjUzOTcxYyIsInJvbGUiOiJVU0VSIiwiY2FuUmVwb3J0Ijp0cnVlLCJpYXQiOjE3NzY2MTUxOTMsImV4cCI6MTc3NjcwMTU5M30.zAGuBizjAfs4YLEi0GAQi2Y2ynPBy2itI0IG67heZfI

{
    "status": "COMPLETED"
}

###
GET http://localhost:8000/api/v1/reports/8700cf80-f6d6-475c-b947-f499badc1360/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVhZDY3NTRmLWYzZDktNGUwMy04ZDQ1LWY4NzdhMjUzOTcxYyIsInJvbGUiOiJVU0VSIiwiY2FuUmVwb3J0Ijp0cnVlLCJpYXQiOjE3NzY2MTUxOTMsImV4cCI6MTc3NjcwMTU5M30.zAGuBizjAfs4YLEi0GAQi2Y2ynPBy2itI0IG67heZfI